/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AccountCreateRequest } from './models/AccountCreateRequest';
export type { AccountResponse } from './models/AccountResponse';
export type { AccountUpdateRequest } from './models/AccountUpdateRequest';
export type { AdminFullResponse } from './models/AdminFullResponse';
export type { AdminInfoResponse } from './models/AdminInfoResponse';
export type { AdminInfoUpdateRequest } from './models/AdminInfoUpdateRequest';
export type { AdminResponse } from './models/AdminResponse';
export { AdminTypes } from './models/AdminTypes';
export type { AdminUpdateRequest } from './models/AdminUpdateRequest';
export type { Body_create_photos_api_v1_hotels__hotel_id__photos_post } from './models/Body_create_photos_api_v1_hotels__hotel_id__photos_post';
export type { Body_create_photos_api_v1_rooms__room_id__photos_post } from './models/Body_create_photos_api_v1_rooms__room_id__photos_post';
export type { Body_upload_menu_api_v1_room_services__room_service_id__menu_post } from './models/Body_upload_menu_api_v1_room_services__room_service_id__menu_post';
export type { ChangePasswordIn } from './models/ChangePasswordIn';
export { ContactTypes } from './models/ContactTypes';
export type { DrufflerFullResponse } from './models/DrufflerFullResponse';
export type { DrufflerInfoResponse } from './models/DrufflerInfoResponse';
export type { HotelAccommodations } from './models/HotelAccommodations';
export type { HotelAccommodationsResponse } from './models/HotelAccommodationsResponse';
export type { HotelAccommodationsUpdateRequest } from './models/HotelAccommodationsUpdateRequest';
export type { HotelAddressResponse } from './models/HotelAddressResponse';
export type { HotelAddressUpdateRequest } from './models/HotelAddressUpdateRequest';
export type { HotelBenefitsCreateRequest } from './models/HotelBenefitsCreateRequest';
export type { HotelBenefitsLink } from './models/HotelBenefitsLink';
export type { HotelBenefitsResponse } from './models/HotelBenefitsResponse';
export type { HotelBenefitsUpdateRequest } from './models/HotelBenefitsUpdateRequest';
export type { HotelContactsResponse } from './models/HotelContactsResponse';
export type { HotelContactsUpdateRequest } from './models/HotelContactsUpdateRequest';
export type { HotelFullResponse } from './models/HotelFullResponse';
export type { HotelMessengersResponse } from './models/HotelMessengersResponse';
export type { HotelMessengersUpdateRequest } from './models/HotelMessengersUpdateRequest';
export type { HotelPhotosResponse } from './models/HotelPhotosResponse';
export type { HotelPhotosUpdateRequest } from './models/HotelPhotosUpdateRequest';
export type { HotelResponse } from './models/HotelResponse';
export { HotelStateTypes } from './models/HotelStateTypes';
export type { HotelUpdateRequest } from './models/HotelUpdateRequest';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { JwtToken } from './models/JwtToken';
export type { NewPasswordIn } from './models/NewPasswordIn';
export type { PasswordIn } from './models/PasswordIn';
export type { RefreshToken } from './models/RefreshToken';
export type { RoomBedsCreateRequest } from './models/RoomBedsCreateRequest';
export type { RoomBedsLinkRequest } from './models/RoomBedsLinkRequest';
export type { RoomBedsResponse } from './models/RoomBedsResponse';
export type { RoomBenefitsCreateRequest } from './models/RoomBenefitsCreateRequest';
export type { RoomBenefitsLink } from './models/RoomBenefitsLink';
export type { RoomBenefitsResponse } from './models/RoomBenefitsResponse';
export type { RoomBenefitsUpdateRequest } from './models/RoomBenefitsUpdateRequest';
export { RoomCategoryTypes } from './models/RoomCategoryTypes';
export type { RoomPhotosResponse } from './models/RoomPhotosResponse';
export type { RoomPhotosUpdateRequest } from './models/RoomPhotosUpdateRequest';
export type { RoomsCreateRequest } from './models/RoomsCreateRequest';
export type { RoomServiceCreateRequest } from './models/RoomServiceCreateRequest';
export type { RoomServiceFullResponse } from './models/RoomServiceFullResponse';
export type { RoomServiceMenuFullResponse } from './models/RoomServiceMenuFullResponse';
export type { RoomServiceMenuItemResponse } from './models/RoomServiceMenuItemResponse';
export type { RoomServiceMenuItemUpdateRequest } from './models/RoomServiceMenuItemUpdateRequest';
export type { RoomServiceMenuResponse } from './models/RoomServiceMenuResponse';
export type { RoomServiceMenuUpdateRequest } from './models/RoomServiceMenuUpdateRequest';
export type { RoomServiceResponse } from './models/RoomServiceResponse';
export { RoomServicesTypes } from './models/RoomServicesTypes';
export type { RoomServiceUpdateRequest } from './models/RoomServiceUpdateRequest';
export type { RoomsFullResponse } from './models/RoomsFullResponse';
export type { RoomsResponse } from './models/RoomsResponse';
export type { RoomsUpdateRequest } from './models/RoomsUpdateRequest';
export { StatusResponse } from './models/StatusResponse';
export type { User } from './models/User';
export type { UsernameIn } from './models/UsernameIn';
export type { ValidationError } from './models/ValidationError';

export { AccountsService } from './services/AccountsService';
export { AdminsService } from './services/AdminsService';
export { AdminsInfoService } from './services/AdminsInfoService';
export { DrufflersService } from './services/DrufflersService';
export { HotelAccommodationsService } from './services/HotelAccommodationsService';
export { HotelAddressService } from './services/HotelAddressService';
export { HotelBenefitsService } from './services/HotelBenefitsService';
export { HotelContactsService } from './services/HotelContactsService';
export { HotelMessengersService } from './services/HotelMessengersService';
export { HotelPhotosService } from './services/HotelPhotosService';
export { HotelsService } from './services/HotelsService';
export { RoomsService } from './services/RoomsService';
export { RoomsBedsService } from './services/RoomsBedsService';
export { RoomsBenefitsService } from './services/RoomsBenefitsService';
export { RoomServicesService } from './services/RoomServicesService';
export { RoomServicesMenuService } from './services/RoomServicesMenuService';
export { RoomsPhotosService } from './services/RoomsPhotosService';
export { TokenService } from './services/TokenService';
export { UsersService } from './services/UsersService';
export { WebSocketService } from './services/WebSocketService';
export { WebSocketTestHtmlPageService } from './services/WebSocketTestHtmlPageService';
